### ISSUE TITLE
[Style] 버튼 스타일링 추가

### ISSUE THREAD

**Issue by duwlsssss** [Dev-FE-2/toy-project1-team2-intranet-project#25]
## 📄 Describe

- global.css
```css
button[color='transparent'][shape='line'] {
    background-color: transparent;
    border: 1.5px solid var(--color-black);
    color: var(--color-black);
  }
  button[color='transparent'][shape='line']:hover {
    background: var(--color-dark-gray);
    color: var(--color-white);
  }
```

-blabla.js
```js
container.innerHTML = `
  <button color="transparent" shape="line">홈으로</button>
`;
```
이런 형식으로 사용할 버튼 스타일을 만들기

## ✅ Tasks

- [ ] 버튼 스타일링 추가
